import mongoose from 'mongoose';

const NewSelectedStaySchema = new mongoose.Schema(
  {
    best_price: { type: Number, required: true },
    zone: { type: String, required: true },
    banner: { type: [String], required: true },
    destination: { type: String, required: true },
    state: { type: String, required: true },
    featured_video: {
      video: { type: String },
      banner: { type: String },
    },
    traveller: { type: String, required: true },
    timestamp: { type: String, required: true },
    story: { type: String, required: true },
    amenities: [
      {
        icon: { type: String },
        label: { type: String },
      },
    ],
    highlight: {
      title: { type: String },
      summary: { type: String },
      gallery: [{ type: String }],
    },
    friend: {
      story: { type: String },
      name: { type: String },
      job: { type: String },
      profile_picture: { type: String },
      video: { type: String },
    },
    rating: {
      overall: { type: Number },
      location: { type: Number },
      rooms: {
        space: { type: Number },
        design: { type: Number },
        amenities: { type: Number },
        view: { type: Number },
      },
      property: {
        size: { type: Number },
        greenery: { type: Number },
        amenities: { type: Number },
        architecture: { type: Number },
      },
      cleanliness: {
        rooms: { type: Number },
        bathrooms: { type: Number },
        restaurant: { type: Number },
        staff: { type: Number },
      },
      food: {
        taste: { type: Number },
        variety: { type: Number },
        unqiue: { type: Number },
        quantity: { type: Number },
      },
      service: {
        room_service: { type: Number },
        courtesy: { type: Number },
      },
      hospitality: { type: Number },
      value: {
        food: { type: Number },
        rooms: { type: Number },
      },
    },
    expert_review: {
      expert: { type: String },
      experience: { type: String },
      highlight: { type: String },
      improvements: { type: String },
      tip: { type: String },
      recommendation: { type: String },
      location: { type: String },
      profile_picture: { type: String },
      bio: { type: String },
      website: { type: String },
      twitter: { type: String },
      facebook: { type: String },
      instagram: { type: String },
      gallery: [{ type: String }],
    },
    policy: [
      {
        title: { type: String },
        text: { type: String },
      },
    ],
    mlos: { type: Number, default: 0 },
    details: {
      actualName: { type: String },
      address: { type: String },
      checkInTime: { type: String },
      checkOutTime: { type: String },
      phoneNumber: { type: String },
      roomsCount: { type: String },
      guestsCount: { type: String },
      stayDescription: { type: String },
      mlosInput: { type: String },
      mlosWeekendInput: { type: String },
      weekday: [{ type: String }],
      weekend: [{ type: String }],
      stayOwnerEmail: { type: String },
      stayConvenienceValue: { type: String },
      stayIgstValue: { type: String },
      stayCgstValue: { type: String },
      staySgstValue: { type: String },
      stayYuyiiiFriendValue: { type: Boolean },
      stayYuyiiiHighlightValue: { type: Boolean },
      stayYuyiiiReviewValue: { type: Boolean },
      stayYuyiiiGuestValue: { type: Boolean },
    },
    status: { type: String },
    hg_id: { type: String, default: null },
    activities: [
      {
        icon: { type: String },
        label: { type: String },
      },
    ],
    name: { type: String },
    stayId: { type: String },
    stayType: [{ type: String }],
    tripType: [{ type: String }],
    activitytags: [{ type: String }],
    staytags: [{ type: String }],
    overview: {
      text: { type: String },
      badge: { type: String },
      ratingoverall: { type: String },
      staytags: [{ type: String }],
      activitytags: [{ type: String }],
    },
    stayvideo: { type: String },
    images: [{ type: String }],
    review: {
      image: { type: String },
      reviewerName: { type: String },
      location: { type: String },
      review: { type: String },
      improvement: { type: String },
      highlight: { type: String },
      experience: { type: String },
      reviewerdesignation: { type: String },
      tip: { type: String },
      suitable: { type: String },
      propertyImage: [{ type: String }],
      socialLinks: [
        {
          icon: { type: String },
          url: { type: String },
        },
      ],
    },
    room: [
      {
        id: { type: String },
        name: { type: String },
        images: [{ type: String }],
        amenities: [{ type: String }],
        price: { type: Number },
        view: { type: String },
      },
    ],
    gallery: {
      type: Map,
      of: [String],
    },
  },
  { timestamps: true }
);

export default mongoose.model("NewSelectedStay", NewSelectedStaySchema, "newselectedstay");
